### ISSUE TITLE
✨[Feature] API 설계 - account/friends

### ISSUE THREAD

**Issue by whaleshade** [Match-Box-Team/BackEnd#1]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 채팅방 관련 백엔드 API 설계

## 📝 기능 상세 내용

- API

## ✅ TODO

- [x] 채팅방 API 설계
