### ISSUE TITLE
✨[Feature] 게임 준비 방 생성

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/BackEnd#103]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 게임 매칭 시 준비 방 모달 보여주기

## 📝 기능 상세 내용

- 게임 매칭 시 준비 방 모달 보여주기

## ✅ TODO

- [x] 게임 매칭 시 게임 준비 모달을 보여줘야함.
- [x] 방장 화면 기준으로 동일한 화면을 보여줘야함
