### ISSUE TITLE
🚨 [Bug] 친구 조회 api 수정

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/BackEnd#106]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 🐛 버그 개요

- Friend API에서 중복되는 url 발견

## 🐞 버그 상세 내용

- 친구 목록 조회 url과 친구 추가를 위한 친구 조회 url 중복됨.
- 친구 조회 url을 /friends/search?nickname=""으로 수정.

## ✅ TODO

- [x] 친구 조회 url을 /friends/search?nickname=""으로 수정.
