### ISSUE TITLE
♻️ [Refactor] 친구 상세 프로필에서 친구가 아닌 경우 고려

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/BackEnd#109]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- 친구 상세 프로필에서 친구가 아닌 경우 고려

## 📝 리팩토링 상세 내용

- 친구 상세 프로필에서 친구가 아닌 경우 고려

## ✅ TODO

- [x] 친구 상세 프로필에서 친구가 아닌 경우 고려
