### ISSUE TITLE
♻️ [Refactor] 디엠일 때 채팅방 이름 추출 & 이전에 dm방을 나갔다가 다시 들어간 경우

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/BackEnd#112]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- 디엠일 때 채팅방 이름 추출 & 이전에 dm방을 나갔다가 다시 들어간 경우

## 📝 리팩토링 상세 내용

- 디엠일 때 채팅방 이름 추출 & 이전에 dm방을 나갔다가 다시 들어간 경우

## ✅ TODO

- [x] 디엠일 때 채팅방 이름 추출
- [x] 이전에 dm방을 나갔다가 다시 들어간 경우
