### ISSUE TITLE
✨[Feature] 매칭 유저 게임 연결

### ISSUE THREAD

**Issue by whaleshade** [Match-Box-Team/BackEnd#116]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 매칭 유저 게임 연결 백엔드

## 📝 기능 상세 내용

- 유저가 소켓으로 매칭되면 게임으로 연결해줌

## ✅ TODO

- [x] 매칭 유저와 관련한 gamehistory create
- [x] 게임 승패 기록
