### ISSUE TITLE
♻️ [Refactor] 관전 목록 페이지 - 게임 관전 목록 조회 API 수정 => matchID도 api에 포함

### ISSUE THREAD

**Issue by Joo-hyun-Kang** [Match-Box-Team/BackEnd#118]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

게임 관전 페이지 구현 시 필요한 MatchID를 받아오기 위해서 게임 관전 목록 조회 API 수정 

## 📝 리팩토링 상세 내용

위와 동일

## ✅ TODO

- [x] matchID도 api에 포함
- [x] 포스트 맨 API 문서 수정
