### ISSUE TITLE
♻️ [Refactor] 채팅방을 나간 유저의 채팅 내역 관리

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/BackEnd#120]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- 채팅방을 나간 유저의 채팅 내역 관리

## 📝 리팩토링 상세 내용

- 채팅방을 나간 유저의 채팅 내역 관리하기 위해 스키마 수정

## ✅ TODO

- [x] 채팅방을 나간 유저의 채팅 내역 관리를 위한 스키마 수정
- [x] 채팅방을 나간 유저의 채팅 내역 관리를 위한 코드 수정
