### ISSUE TITLE
✨[Feature]  게임 socket room 구분

### ISSUE THREAD

**Issue by whaleshade** [Match-Box-Team/BackEnd#123]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- socket io 의 room 기능 추가

## 📝 기능 상세 내용

- 이전까지는 게임 소켓으로 연결된 게임이 하나라고 가정했지만, room을 이용해 여러개를 구현

## ✅ TODO

- [x] socket room 삽입
- [x] 게임 테스트
