### ISSUE TITLE
♻️ [Refactor] API 수정 : 유저 게임 히스토리

### ISSUE THREAD

**Issue by Joo-hyun-Kang** [Match-Box-Team/BackEnd#127]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

유저게임 히스토리
  - 게임을 가지고 있지 않을 때 컨플릭트 반환하도록 설정
  - 게임 히스토리에서 게임히스토리 ID를 반환하게 설정

## 📝 리팩토링 상세 내용

프론트 매치 히스토리 페이지를 만들 때 구매하지 않은 게임에 대해서 오류 메세지를 띄우기 위해서 수정
프론트 매치 히스토리 페이지를 만들 때 map을 돌릴 키가 필요해서 게임 히스토리 ID 추가

## ✅ TODO

유저게임 히스토리
- [x] 게임을 가지고 있지 않을 때 컨플릭트 반환하도록 설정
- [x] 게임 히스토리에서 게임히스토리 ID를 반환하게 설정
