### ISSUE TITLE
♻️ [Refactor] ismute와 isadmin 조회

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/BackEnd#129]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- ismute와 isadmin 조회

## 📝 리팩토링 상세 내용

- ismute와 isadmin 조회

## ✅ TODO

- [x] ismute와 isadmin 조회
