### ISSUE TITLE
✨[Feature] 게임 관전

### ISSUE THREAD

**Issue by whaleshade** [Match-Box-Team/BackEnd#132]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 게임 관전 기능

## 📝 기능 상세 내용

- 일정 수의 소켓을 특정 게임에 join시켜주기

## ✅ TODO

- [ ] 프론트에서 요청온 내용 바탕으로 join 시키기
