### ISSUE TITLE
✨[Feature] 매칭 취소, 게임 중 나감 등등 처리

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/BackEnd#136]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

매칭 취소, 게임 중 나감 등등 처리
## 📝 기능 상세 내용

매칭 취소, 게임 중 나감 등등 처리
## ✅ TODO

- [x] 랜덤 매칭 취소
- [x] 게임 중 gg, 나갔을 때 처리
