### ISSUE TITLE
♻️ [Refactor] 채팅 에러 메시지 변경

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/BackEnd#138]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- 채팅 에러 메시지 변경

## 📝 리팩토링 상세 내용

- 채팅 에러 메시지 변경

## ✅ TODO

- [x] 채팅 에러 메시지 변경
