### ISSUE TITLE
🚨 [Bug] 킥 당한 유저의 소켓 연결 해제 시 에러

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/BackEnd#140]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 🐛 버그 개요

- 킥 당한 유저의 소켓 연결 해제 시 에러

## 🐞 버그 상세 내용

- 킥 당한 유저의 소켓 연결 해제 시 에러

## ✅ TODO

- [x] 킥 당한 유저의 소켓 연결 해제 시 에러 해결
