### ISSUE TITLE
🚨 [Bug] 게임 관련 버그들 수정

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/BackEnd#142]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 🐛 버그 개요

게임 관련 버그들 수정

## ✅ TODO

- [x] 게임 구매 안한 유저가 게임 초대를 하는 경우 막기
- [x] 게임 구매 안한 유저에게 게임 초대를 하는 경우 막기
- [x] 게임 준비 페이지에서 닉네임 안뜸
- [x] 게임 끝났을 때 이긴 유저의 닉네임 안뜸
