### ISSUE TITLE
✨[Feature] 게임 컨트롤러 init 될 때 게임들 시딩하기(이미 게임들 시딩된 상태면 동작안함)

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/BackEnd#148]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 게임 컨트롤러 init 될 때 게임들 시딩하기 -> 이미 시딩되어 있으면 동작 안함

## 📝 기능 상세 내용

- 게임 컨트롤러 init 될 때 게임들 시딩하기

## ✅ TODO

- [x] 게임 컨트롤러 init 될 때 게임들 시딩하기
