### ISSUE TITLE
♻️ [Refactor] 인증 메일 양식 수정 및 console.log 제거

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/BackEnd#150]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- 인증 메일 양식 수정 및 console.log 제거

## 📝 리팩토링 상세 내용

- 인증 메일 양식 수정 및 console.log 제거

## ✅ TODO

- [x] 인증 메일 양식 수정 및 console.log 제거
