### ISSUE TITLE
🚨 [Bug] 랜덤 매칭 에러

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/BackEnd#154]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 🐛 버그 개요

- 랜덤 매칭 에러

## 🐞 버그 상세 내용

- 랜덤 매칭 에러

## ✅ TODO

- [x] 랜덤 매칭 에러
