### ISSUE TITLE
🚨 [Bug] 게임 준비 취소

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/BackEnd#156]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 🐛 버그 개요

- 게임 준비 취소

## 🐞 버그 상세 내용

- 게임 준비 취소

## ✅ TODO

- [x] 게임 준비 취소
