### ISSUE TITLE
🚨 [Bug] 게임 오류 및 await 추가

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/BackEnd#161]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 🐛 버그 개요

- 게임 오류 및 await 추가

## 🐞 버그 상세 내용

- 게임 오류 및 await 추가

## ✅ TODO

- [x] 게임 오류 및 await 추가
