### ISSUE TITLE
♻️ [Refactor] 콘솔 로그 주석 처리

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/BackEnd#164]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- 콘솔 로그 주석 처리

## 📝 리팩토링 상세 내용

- 콘솔 로그 주석 처리

## ✅ TODO

- [x] 콘솔 로그 주석 처리
