### ISSUE TITLE
♻️ [Refactor]게임 로직 any 제거

### ISSUE THREAD

**Issue by whaleshade** [Match-Box-Team/BackEnd#170]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- 게임 로직에 적용된 any 타입을 제거

## 📝 리팩토링 상세 내용

- any 타입을 strict한 타입으로 변경

## ✅ TODO

- [ ] any 타입 변경
