### ISSUE TITLE
♻️ [Refactor] gameWatchId 없는 방 들어갔을 때 처리 및 playGame쪽 any 수정

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/BackEnd#171]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- gameWatchId 없는 방 들어갔을 때 처리 및 playGame쪽 any 수정

## 📝 리팩토링 상세 내용

- gameWatchId가 없는 방으로 접속했을 때 마이 프로필 페이지로 리다이랙션 시킴
- playGame과 관련된 코드 중 any가 있는 부분을 수정함

## ✅ TODO

- [x] gameWatchId가 없는 방으로 접속했을 때 마이 프로필 페이지로 리다이랙션 시킴
- [x] playGame과 관련된 코드 중 any가 있는 부분을 수정함
