### ISSUE TITLE
🚨 [Bug] 게임 이동 관련 버그(뒤로 가기 새로고침 등등) 처리

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/BackEnd#173]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 🐛 버그 개요

- 게임 이동 관련 버그(뒤로 가기 새로고침 등등) 처리

## 🐞 버그 상세 내용

게임 이동 관련 버그(뒤로 가기 새로고침 등등) 처리

## ✅ TODO

- [ ] 게임 준비 관련 처리
