### ISSUE TITLE
♻️ [Refactor] 내가 속한 채널 목록 페이지의 오너 정보 전달

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/BackEnd#175]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- 내가 속한 채널 목록 페이지의 오너 정보 전달

## 📝 리팩토링 상세 내용

- 내가 속한 채널 목록 페이지의 오너 정보 전달

## ✅ TODO

- [x] 내가 속한 채널 목록 페이지의 오너 정보 전달
