### ISSUE TITLE
🚨 [Bug] 코드 정리 마무리

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/BackEnd#177]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 🐛 버그 개요

코드 정리 마무리

## 🐞 버그 상세 내용

코드 정리 마무리

## ✅ TODO

- [x] 코드 정리 마무리
