### ISSUE TITLE
✨[Feature] 채팅 관련 소켓 연결 구현

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/BackEnd#19]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 채팅방 들어갔을 때 소켓 연결 구현
- 채팅방 안에서 메시지 보낼 때의 소켓 연결 구현

## 📝 기능 상세 내용

- 채팅방 관련 소켓 연결하고, 관련 API 연결

## ✅ TODO

- [ ] 채팅방 들어갈 때 소켓 연결
- [ ] 채팅방 안에서 채팅 메시지 연결
