### ISSUE TITLE
✨[Feature] API 설계 - 게임

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/BackEnd#2]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 백엔드 친구 목록 API 설계

## 📝 기능 상세 내용

- 구현 관련 상세 내용 작성

## ✅ TODO

- [ ] 게임 API 설계
