### ISSUE TITLE
✨[Feature] ERD  GameWatch 수정

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/BackEnd#20]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

ERD  GameWatch 수정

## 📝 기능 상세 내용

ERD  GameWatch 수정 -> gameId, userId 관련 수정, UserGame과 연결

## ✅ TODO

- [x] ERD  GameWatch 수정
