### ISSUE TITLE
✨[Feature] 소켓으로 유저(online, offline) 상태 업데이트 구현

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/BackEnd#22]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

소켓으로 유저(online, offline) 상태 업데이트 구현

## 📝 기능 상세 내용

소켓 연결 시 유저 상태 online으로 변경
소켓 끊길 시 유저 상태 offline으로 변경

## ✅ TODO

- [x] 소켓으로 유저(online, offline) 상태 업데이트 구현
