### ISSUE TITLE
✨[Feature] 게임관련 소켓 연결 구현

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/BackEnd#24]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 게임 관련 api 구현
- 게임 매칭 관련 소켓 연결 구현
- 어쩌다 보니 이메일 인증까지... 다음엔 구분해서 브랜치에 커밋하겠습니당
 
## 📝 기능 상세 내용

- 게임과 관련된 api 구현
- 게임과 관련된 소켓 연결 구현
- 메일 인증 기능 구현

## ✅ TODO

- [x] 게임 목록 조회
- [x] 게임 구매
- [x] 게임 관전 목록 조회
- [x] 게임 종료
- [x] 메일로 인증 코드 전송
- [x] 코드 인증
