### ISSUE TITLE
✨[Feature] Channel Api 구현

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/BackEnd#26]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- Channel Api 구현

## 📝 기능 상세 내용

- TODO에 표시

## ✅ TODO

- [ ] 공개 채널 - 채널 조회
- [ ] 공개 채널 - 내가 속한 채널 조회
- [ ] 공개 채널 - 채널 만들기
- [ ] 채팅방 페이지 - 채팅방 입장
- [x] 채팅방 페이지 - 채팅 로그 가져오기
- [x] 채팅 작성
- [ ] 친구 초대
- [ ] 친구 조회 결과(친구 초대 검색할 때)
- [ ] 채팅방 설정
- [ ] 친구(채팅방 멤버) 목록
- [ ] 친구 추가
