### ISSUE TITLE
✨[Feature] API설계 - 채널

### ISSUE THREAD

**Issue by Joo-hyun-Kang** [Match-Box-Team/BackEnd#3]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

ERD 도출 후 백엔드 구현을 위한 API 설계

## 📝 기능 상세 내용

채널 부분 API 설계로 피그마 디자인을 보고 각 페이지별로 사용할 api 설계

## ✅ TODO

- [x] 채널 목록 페이지
- [ ] 

## 📍 레퍼런스

https://www.notion.so/API-a7a7f31bdaa742b186b60bf10b49b72d
https://www.figma.com/file/dPf3kOvTl8148sEmLh8way/DesignFlow?node-id=0-1&t=GQnSeaA9H3nK507M-0
