### ISSUE TITLE
✨[Feature] channel api: 친구(=채팅방 멤버) 목록, 나가기

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/BackEnd#32]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- channel api 구현

## 📝 기능 상세 내용

- 채팅방 페이지 - 채팅방 멤버 목록 api
- 채팅방 페이지 - 나가기 api

## ✅ TODO

- [x] 채팅방 페이지 - 채팅방 멤버 목록 api
- [x] 채팅방 페이지 - 나가기 api
