### ISSUE TITLE
♻️ [Refactor] Oauth를 통해서 프로필 이미지를 최초에만 가져오게 수정

### ISSUE THREAD

**Issue by Joo-hyun-Kang** [Match-Box-Team/BackEnd#35]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

Oauth를 통해서 프로필 이미지를 최초에만 가져오게 수정
우리 서비스에서 유저가 자신의 이미지를 바꿀 수 있기 때문에
로그인 할 때마다 이미지를 업데이트하면 안 됌

## ✅ TODO

- [ ] Oauth에서 최초 로그인 할 때와 업데이트할 때 구분해야 함
