### ISSUE TITLE
♻️ [Refactor] channel/repository에서 request 타입 지정 및 아이디 추출

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/BackEnd#36]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- channel/repository에서 request 타입 지정 및 아이디 추출

## 📝 리팩토링 상세 내용

- channel/repository에서 request 타입 지정 및 아이디 추출

## ✅ TODO

- [x] request 타입 지정
- [x] 아이디 추출
