### ISSUE TITLE
✨[Feature] 백엔드 API 개발

### ISSUE THREAD

**Issue by Joo-hyun-Kang** [Match-Box-Team/BackEnd#38]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 채팅방 페이지 : 친구(=채팅방 멤버)를 친구로 추가 --> friends api 친구 추가 재활용
- 채팅방 페이지 : 킥 
- 친구 추가(닉네임) : 친구추가
- 친구의 게임 전적 페이지 : 친구의 게임 전적 조회

## 📝 기능 상세 내용

- 채팅방 페이지 : 친구(=채팅방 멤버)를 친구로 추가
- 채팅방 페이지 : 킥 
- 친구의 게임 전적 페이지 : /friends/:buddyId/history?game=pingpong

## ✅ TODO

- [x] 채팅방 페이지 == 친구(=채팅방 멤버)를 친구로 추가 
- [x] 채팅방 페이지 : 킥 
- [ ] 친구의 게임 전적 페이지 : /friends/:buddyId/history?game=pingpong

**Comment by Joo-hyun-Kang** [comment]
채팅방 페이지 == 친구(=채팅방 멤버)를 친구로 추가 구현완료
