### ISSUE TITLE
✨[Feature] API 설계 - 친구

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/BackEnd#4]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요
API 설계 - 친구

## ✅ TODO
- [ ] 친구 목록 페이지
- [ ] 상대방 프로필 페이지
- [ ] 친구 추가 페이지
- [ ] 친구 상세 목록 페이지
