### ISSUE TITLE
♻️ [Refactor] Game API 예외 처리 로직 수정

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/BackEnd#46]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- Game API 예외 처리 로직 수정

## 📝 리팩토링 상세 내용

- 리팩토링 관련 상세 내용 작성

- (userGameIds === null) 부분 삭제 
  -> findMany가 매칭되는 것이 없으면 빈 배열([])을 반환함.
  [].some() 은 에러가 안나서 에러처리 필요 X
- buyGame 메서드에서 해당 userid, gameid의 userGame이 존재하는지 먼저 확인 -> 중복 체크

## ✅ TODO

- [x] 예외 처리 로직 수정
