### ISSUE TITLE
✨[Feature] auth 2차 인증과, Account API

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/BackEnd#49]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 2차 메일 인증을 1차 oauth인증과 연결
- Account API 완성

## 📝 기능 상세 내용

- 구현 관련 상세 내용 작성

## ✅ TODO

- [x] 2차 메일 인증을 1차 oauth인증과 연결
- [x] MyPage -> 내 정보 보기 및 게임하기/전적보기 요청
- [x] MyPage 프로필 수정 modal -> 프로필 수정
