### ISSUE TITLE
✨[Feature] DB 개발 환경 구축

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/BackEnd#5]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요
DB 개발 환경 구축

### 개발 환경 버전
노드 버전 18.15.0 -> n 18.15.0 명령어로 노드 버전 수정 가능
@nestjs/common": "^9.3.0"

ORM(타입ORM 혹은 프리즈마)를 이용해서 마이그레이션
ORM(타입ORM 혹은 프리즈마)를 이용해서 시딩

## ✅ TODO
- [X] Postgresql 도커로 서버 구동하기
- [x] ORM(prisma)를 이용해서 마이그레이션
- [x] ORM(prisma)를 이용해서 시딩
