### ISSUE TITLE
✨[Feature] 친구 목록 조회 API

### ISSUE THREAD

**Issue by whaleshade** [Match-Box-Team/BackEnd#51]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 친구목록을 조회하는 API

## 📝 기능 상세 내용

- GET /friends API를 요청하면  다음을 반환
```
{
    “friend”: [
        {
            “friendId”: “string”,
            “buddyId”: “string”,
            “isBan”: boolean,
            “buddy”: 
            {
                  “nickname”: “string”,
                  “intraId”: “string”,
                  “status”: "string",
                  “image”: “string”
            },
        },
    ]
}
```

## ✅ TODO

- [x] controller/service/repository 코드 작성
- [x] API 호출 후 리턴값 확인
