### ISSUE TITLE
✨[Feature] 친구 상세 페이지 API

### ISSUE THREAD

**Issue by whaleshade** [Match-Box-Team/BackEnd#52]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 추가할 기능 요약 설명

## 📝 기능 상세 내용

- GET /friends/:friendId
```
{
    "buddy": {
        "nickname": "string",
        "intraId": "string",
        "image": "string",
    },
    “userGame”: [
        “game”: {
            “gameId”: “string”,
            “name”: “string”
        },
        “gameHistory”: {
            “wincounts”: number,
            “losecounts”: number
        }
    ]
}
 ```

## ✅ TODO

- [x] controller/service/repository code 작성
- [x] return 값 테스트
