### ISSUE TITLE
✨[Feature] friends api 친구 추가 페이지 닉네임 검색

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/BackEnd#54]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- Friends API 중 친구 추가(닉네임) 페이지의 닉네임 검색 구현

## 📝 기능 상세 내용

- 친구 추가(닉네임) 페이지 - 닉네임 검색

## ✅ TODO

- [x] 친구 추가(닉네임) 페이지 - 닉네임 검색
