### ISSUE TITLE
♻️ [Refactor] 채널 목록에서 최신 메시지 시간 표시 로직에서 채팅 기록 없는 경우에 대한 수정

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/BackEnd#59]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- 채널 목록에서 최신 메시지 시간 표시 로직에서 채팅 기록 없는 경우에 대한 수정

## 📝 리팩토링 상세 내용

- 채널 생성 시 fake message를 chat 테이블에 생성
- 채팅 로그 불러올 때 fake message 제외하고 반환
- 채널 목록의 각 채널의 최신 메시지 시간 표시에서 채팅 기록 없는 경우 fake message 생성 시간으로 반환

## ✅ TODO

- [x] 채널 생성 시 fake message를 chat 테이블에 생성
- [x] 채팅 로그 불러올 때 fake message 제외하고 반환
- [x] 채널 목록의 각 채널의 최신 메시지 시간 표시에서 채팅 기록 없는 경우 fake message 생성 시간으로 반환
