### ISSUE TITLE
✨[Feature] git협업 환경 구축

### ISSUE THREAD

**Issue by Joo-hyun-Kang** [Match-Box-Team/BackEnd#6]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

협업을 위한 git 플로우
커밋 메세지 양식

## 📝 기능 상세 내용

위와 동일

## ✅ TODO

- [x] 깃 플로우 결정
- [x] 깃 레포 브론치 설정
- [x] 깃 커밋 메세지 양식 넣기

**Comment by Joo-hyun-Kang** [comment]
깃 플로우는 Git Lab flow 사용
