### ISSUE TITLE
♻️ [Refactor] 소켓 useguard 추가

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/BackEnd#60]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- http 통신처럼 소켓에서도 useGuard 사용하여 토큰 검증 및 userId 추출

## 📝 리팩토링 상세 내용

- http 통신처럼 소켓에서도 useGuard 사용하여 토큰 검증 및 userId 추출

## ✅ TODO

- [x] channel 소켓에 useGuard 적용
- [x] account 소켓에 useGuard 적용
- [x] game 소켓에 useGuard 적용
