### ISSUE TITLE
✨[Feature] 초기 intra 이미지 저장과 이미지 업로드 구현

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/BackEnd#62]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 기능 개요

- 초기 인트라 이미지를 서버에 저장
- 이미지 업로드 기능 구현

## 📝 기능 상세 내용

- 초기 인트라 이미지를 저장 -> db User.image도 이미지 파일 주소로 업데이트
- 이미지 업로드 기능 구현 -> 프로필 수정 부분도 서버에 저장된 이미지 파일 주소로 업데이트하도록 수정

## ✅ TODO

- [x] 초기 인트라 이미지 서버에 저장
- [x] 이미지 업로드 기능 구현
