### ISSUE TITLE
♻️ [Refactor] channel api - 채널 생성 api의 response data 생성

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/BackEnd#66]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- 채널 생성 api의 response data 생성

## 📝 리팩토링 상세 내용

- 채널 생성 후 바로 채널 페이지에 들어갈 때 필요한 channelId 반환

## ✅ TODO

- [ ] 이거 하려면 이런 걸 해야해
- [ ] 이것도 해야할 것 같아
