### ISSUE TITLE
♻️ [Refactor] api path variable의 id의 데이터가 uuid인지 체크

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/BackEnd#69]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- api path variable의 id의 데이터가 uuid인지 체크

## 📝 리팩토링 상세 내용

- api path variable의 id의 데이터가 uuid인지 체크

## ✅ TODO

- [x] api path variable의 id의 데이터가 uuid인지 체크
