### ISSUE TITLE
♻️ [Refactor] 프로필 수정 api를 이미지, 닉네임 수정 2개로 나눔

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/BackEnd#77]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

지금 프론트에서 유저 이미지와 닉네임을 한번에 같이 보내는데, 둘다 왔거나 이미지가 안왔을 때는 괜찮은데 
이미지가 안왔을 때의 처리를 실패함.  

## 📝 리팩토링 상세 내용

- 프로필 수정 api를 이미지, 닉네임 수정 2개로 나눔

## ✅ TODO

- [x] 프로필 수정 api 분해
