### ISSUE TITLE
♻️ [Refactor] 이미지 없는 경로일 때 디폴트 이미지를 반환하도록 수정

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/BackEnd#82]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- 이미지 없는 경로일 때 디폴트 이미지를 반환하도록 수정

## 📝 리팩토링 상세 내용

- 이미지 없는 경로일 때 assets/default/default.jpg의 시바이누를 보내도록 함

## ✅ TODO

- [x] 이미지 없는 경로일 때 디폴트 이미지를 반환하도록 수정
