### ISSUE TITLE
🚨 [Bug] channel service의 getMyChannelList time 버그 수정

### ISSUE THREAD

**Issue by whaleshade** [Match-Box-Team/BackEnd#84]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 🐛 버그 개요

- time이 null일때의 처리 이슈 발생

## 🐞 버그 상세 내용

- 서버 처리 에러

## ✅ TODO

- [x] time 특정 문자에 접근 가능한지 확인
