### ISSUE TITLE
♻️ [Refactor] 게임 히스토리 변수명 수정, 게임 컨트롤러 부분 오류 수정

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/BackEnd#86]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- 게임 히스토리에 wincounts -> winCount, loseCounts -> loseCount로 수정
  wincounts로 오타가 있었음
- 게임 컨트롤러에서 param으로 gameId를 받는데, dto로 { gameId: string}으로 받고 있었어서 에러나는 부분 수정

## 📝 리팩토링 상세 내용

- 게임 히스토리의 wincounts -> winCount, loseCounts -> loseCount로 수정
  wincounts로 오타가 있었음
- 게임 컨트롤러에서 param으로 gameId를 받는데, dto로 { gameId: string}으로 받고 있었어서 에러나는 부분 수정

## ✅ TODO

- [x] 게임 히스토리 수정
- [x] 컨트롤러 파라미터 수정
