### ISSUE TITLE
🚨 [Bug] 닉네임 중복 처리 수정

### ISSUE THREAD

**Issue by kimjinho1** [Match-Box-Team/BackEnd#88]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 🐛 버그 개요

- 닉네임 중복 처리 기능을 안 넣어서 추가했습니다.

## 🐞 버그 상세 내용

- 프로필 수정 모달에서 닉네임 중복 처리 기능을 넣는 것을 깜빡해서 서버가 터짐.

## ✅ TODO

- [x] 닉네임 중복 처리 추가
