### ISSUE TITLE
♻️ [Refactor] 유저 정보 api 추가 & 유저 인증 수정

### ISSUE THREAD

**Issue by cofls980** [Match-Box-Team/BackEnd#90]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

- 유저 정보 api 추가 & 유저 인증 수정

## 📝 리팩토링 상세 내용

- 유저 정보 api 추가 & 유저 인증 수정

## ✅ TODO

- [x] 유저 정보 api 추가 & 유저 인증 수정
