### ISSUE TITLE
♻️ [Refactor] 채팅 소켓 API와 채팅 로그 API 형식을 같게 변경

### ISSUE THREAD

**Issue by Joo-hyun-Kang** [Match-Box-Team/BackEnd#92]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 📄 리팩토링 개요

채팅 소켓 API와 채팅 로그 API 형식을 같게 변경

## 📝 리팩토링 상세 내용

기존에 채팅 소켓 API에 chatID와 chatDate가 빠진 걸 추가함
프론트에서 처리하기 쉽게 2개의 API의 인터페이스를 1개로 통일함

## ✅ TODO

- [x] 채팅 소켓 API 변경
- [x] 프론트에서 테스트
